services:
  proxy:
    image: nginx:1.26
    container_name: nginx-proxy
    volumes:
      - ./templates:/etc/nginx/templates
      - "${HOST_CERTS_DIR}:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-router

networks:
  nginx-router:
    name: "nginx-router"
    attachable: true